// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-content.ts
import { createClient } from "npm:@supabase/supabase-js@^2.79.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_content_default = defineTool({
  name: "list_content",
  title: "List study content",
  description: "List the signed-in user's saved study content (analyses and chats), newest first.",
  inputSchema: {
    content_type: z.enum(["analyse", "chat"]).optional().describe("Filter by content type."),
    limit: z.number().int().optional().describe("Max rows to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ content_type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const cap = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("user_content").select("id, title, content_type, language, created_at, generation_status").order("created_at", { ascending: false }).limit(cap);
    if (content_type) query = query.eq("content_type", content_type);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-content.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.79.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_content_default = defineTool2({
  name: "get_content",
  title: "Get study content",
  description: "Fetch a single saved study item (analysis or chat) by id, including analysis data and original text.",
  inputSchema: {
    id: z2.string().uuid().describe("The user_content row id (UUID).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("user_content").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { row: data }
    };
  }
});

// src/lib/mcp/tools/search-content.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.79.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_content_default = defineTool3({
  name: "search_content",
  title: "Search study content",
  description: "Search the signed-in user's study content by title or original text (case-insensitive substring match).",
  inputSchema: {
    query: z3.string().trim().min(1).describe("Search term matched against title and original_text."),
    limit: z3.number().int().optional().describe("Max rows to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const cap = Math.min(Math.max(limit ?? 20, 1), 100);
    const escaped = query.replace(/[%_]/g, (m) => `\\${m}`);
    const pattern = `%${escaped}%`;
    const { data, error } = await supabaseForUser3(ctx).from("user_content").select("id, title, content_type, language, created_at").or(`title.ilike.${pattern},original_text.ilike.${pattern}`).order("created_at", { ascending: false }).limit(cap);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/delete-content.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.79.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var delete_content_default = defineTool4({
  name: "delete_content",
  title: "Delete study content",
  description: "Permanently delete a saved study item (analysis or chat) belonging to the signed-in user.",
  inputSchema: {
    id: z4.string().uuid().describe("The user_content row id (UUID) to delete.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { error } = await supabaseForUser4(ctx).from("user_content").delete().eq("id", id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Deleted ${id}` }],
      structuredContent: { id, deleted: true }
    };
  }
});

// src/lib/mcp/tools/get-plan-info.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.79.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_plan_info_default = defineTool5({
  name: "get_plan_info",
  title: "Get plan and daily usage",
  description: "Return the signed-in user's current Aide plan (free/pro/class) and today's analysis usage count.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = supabaseForUser5(ctx);
    const userId = ctx.getUserId();
    const [{ data: planData }, { data: usageData }] = await Promise.all([
      client.rpc("get_user_plan", { p_user_id: userId }),
      client.rpc("get_daily_usage_count", { p_user_id: userId })
    ]);
    const info = {
      user_id: userId,
      email: ctx.getUserEmail(),
      plan: planData ?? "free",
      daily_usage_count: usageData ?? 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "obiiwmdcykfredsbhmoc";
var mcp_default = defineMcp({
  name: "aide-mcp",
  title: "Aide Study MCP",
  version: "0.1.0",
  instructions: "Tools for Aide, an AI study companion. Use `list_content` and `search_content` to find the signed-in user's saved analyses and chats, `get_content` for the full analysis payload (summary, key terms, quiz, flashcards, knowledge map), `delete_content` to remove an item, and `get_plan_info` for their current plan and today's usage.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_content_default,
    get_content_default,
    search_content_default,
    delete_content_default,
    get_plan_info_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
